FROM nginx:1.15-alpine

ARG HOST
ARG PORT

ENV HOST ${HOST}
ENV PORT ${PORT}

RUN apk update && apk add py-pip
RUN pip install j2cli

COPY nginx.conf.j2 nginx.conf.j2
RUN j2 nginx.conf.j2 > /etc/nginx/nginx.conf
