# Generated by Django 3.0 on 2019-12-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mem',
            name='url',
        ),
        migrations.AddField(
            model_name='mem',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
