# Generated by Django 3.0 on 2019-12-20 08:23

from django.db import migrations, models
import memes.models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0002_auto_20191219_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=256)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='mem',
            name='image',
            field=models.ImageField(default=None, upload_to=memes.models.Post.upload_to),
        ),
    ]
